'use client';
import {useState} from 'react';
import {CartesianGrid,LineChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis,ReferenceLine} from 'recharts';
import {MarketTable,TrendChart} from '../MarketCharts';
import type {AskPoint} from '@/lib/market-extras';
import type {MacroPoint,MarketData} from '@/lib/market-data';
export function MarketHistory({history,asks}:{history:MacroPoint[];asks:AskPoint[]}){const [period,setPeriod]=useState(36);const end=history.at(-1)?.month;const cutoff=end?new Date(`${end}-01T00:00:00Z`):null;if(cutoff)cutoff.setUTCMonth(cutoff.getUTCMonth()-period+1);const series=period&&cutoff?history.filter(p=>p.month>=cutoff.toISOString().slice(0,7)):history;
 const latest=asks.at(-1),previous=asks.at(-2);const delta=latest&&previous?latest.market_recovery_index-previous.market_recovery_index:null;
 return <><section className="rt-panel"><div className="rt-heading"><h2>월별 실거래 추이</h2><div className="rt-tabs">{[[12,'1년'],[36,'3년'],[60,'5년'],[0,'전체']].map(([v,label])=><button key={v} aria-pressed={period===v} className={period===v?'active':''} onClick={()=>setPeriod(Number(v))}>{label}</button>)}</div></div><p>{series[0]?.month||'자료 없음'} ~ {series.at(-1)?.month||'—'} · {series.length}개 관측 월</p><TrendChart data={series}/><p className="rt-caption">막대는 유효 신고 거래 수, 선은 고점 대비 실거래 회복률입니다. 당월은 잠정치이며 누락된 월을 보간하지 않습니다.</p></section><section className="rt-panel"><div className="rt-heading"><div><div className="rf-eyebrow">ASKING PRICE / OBSERVATIONS</div><h2>매도자의 기대 가격, 호가 회복률</h2></div><strong className="rf-number rf-mint" style={{fontSize:26}}>{latest?`${latest.market_recovery_index.toFixed(2)}%`:'미수집'}</strong></div><p>{latest?`${latest.date} · 유효 타입 표본 ${latest.sample_count}개`: '호가 시계열이 없습니다.'}{delta!==null?` · 이전 관측(${previous!.date}) 대비 ${delta>0?'+':''}${delta.toFixed(2)}%p`:''}</p><div className="rt-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={asks} margin={{top:12,right:12,left:0,bottom:0}}><CartesianGrid stroke="#253442" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} stroke="#91a5b7" tick={{fontSize:10}} minTickGap={32}/><YAxis domain={['auto','auto']} unit="%" stroke="#91a5b7" tick={{fontSize:10}}/><ReferenceLine y={100} stroke="#667d8a" strokeDasharray="4 4" ifOverflow="extendDomain"/><Tooltip contentStyle={{background:'#13212c',border:'1px solid #3c5261',fontSize:12}}/><Line isAnimationActive={false} type="linear" dataKey="market_recovery_index" name="호가 회복률(%)" stroke="#8fe0c6" strokeWidth={2} dot={asks.length<3}/></LineChart></ResponsiveContainer></div><p className="rt-caption">{asks[0]?.date||'—'} ~ {latest?.date||'—'} · {asks.length}개 관측일. 일별 유효 타입의 최저호가 ÷ 관측 최고 실거래가 비율 중앙값입니다. 일별 표본과 고점 기준이 달라질 수 있으며 동일 매물의 가격 변동률이 아닙니다. 수집 전 기간은 생성하지 않습니다.</p></section></>;
}
export function TypeRankings({representatives,allTypes}:{representatives:MarketData['rows'];allTypes:MarketData['rows']}){const [view,setView]=useState('representative');const [recent,setRecent]=useState(true);const source=view==='all'?allTypes:representatives;const rows=recent?source.filter(r=>r.gap!==null&&r.age!==null&&r.age<=365):source;return <section className="rt-panel"><div className="rt-heading"><h2>단지·타입별 가격 괴리</h2><div className="rt-tabs"><button aria-pressed={view==='representative'} className={view==='representative'?'active':''} onClick={()=>setView('representative')}>대표 타입</button><button aria-pressed={view==='all'} className={view==='all'?'active':''} onClick={()=>setView('all')}>전체 타입</button></div></div><p>{view==='all'?'같은 단지의 여러 타입이 함께 표시됩니다. 거래 원천이 같은 타입들이 포함될 수 있어 거래 건수를 합산하지 않습니다.':'단지별 대표 타입 하나씩 비교합니다.'}</p><label className="rt-small" style={{display:'block',margin:'14px 0'}}><input type="checkbox" checked={recent} onChange={e=>setRecent(e.target.checked)}/> 최근 365일 거래·현재 호가가 있는 타입만</label><MarketTable rows={rows}/></section>;}
