'use client';
import {useEffect,useState,useSyncExternalStore} from 'react';
import Link from 'next/link';
import {outlookLabel,parseLocal,opinionDistribution,type Opinion,type Outlook} from '@/lib/community-model';
import {price} from '@/lib/complex-model';
import './community.css';
import {useMember,memberRequest} from './MemberProvider';
import useWatchlist from './useWatchlist';
const KEY='realfifty-local-opinions-v1';
const subscribe=(cb:()=>void)=>{window.addEventListener('storage',cb);window.addEventListener('rf-community',cb);window.addEventListener('rf-watchlist',cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener('rf-community',cb);window.removeEventListener('rf-watchlist',cb);};};
const read=(key:string)=>{try{return localStorage.getItem(key)||'[]';}catch{return '[]';}};
const empty=()=>'[]';
const labels={user:'사용자 의견',ai:'AI 페르소나',unknown:'작성 유형 미확인',local:'내 로컬 의견'};
export default function CommunityPanel({complexId,complexName,areaLabel,trade,ask}:{complexId?:string;complexName?:string;area?:string;areaLabel?:string;trade?:number|null;ask?:number|null}){
 const {user,requireLogin,ready}=useMember();const {watched}=useWatchlist();
 const localRaw=useSyncExternalStore(subscribe,()=>read(KEY),empty);const local=parseLocal(localRaw);
 const [saving,setSaving]=useState(false),[revision,setRevision]=useState(0);
 const [kind,setKind]=useState('user'),[filter,setFilter]=useState('all'),[remote,setRemote]=useState<Opinion[]>([]),[status,setStatus]=useState('loading'),[checked,setChecked]=useState('');
 const [name,setName]=useState(''),[content,setContent]=useState(''),[vote,setVote]=useState<Outlook>('neutral'),[message,setMessage]=useState('');
 useEffect(()=>{let stopped=false;let controller:AbortController|null=null;async function refresh(){controller?.abort();controller=new AbortController();try{const bodies=await Promise.all((kind==='all'?['user','ai']:[kind]).map(async k=>{const res=await fetch(`/api/community?kind=${k}${complexId?`&complex=${encodeURIComponent(complexId)}`:''}`,{signal:controller!.signal});return res.json();}));const body={comments:bodies.flatMap(b=>b.comments||[]),status:bodies.some(b=>b.status==='error')?'error':bodies[0].status,checkedAt:bodies[0].checkedAt};if(!stopped){setRemote(body.comments||[]);setStatus(body.status);setChecked(body.checkedAt||'');}}catch(e){if(!stopped&&(e as Error).name!=='AbortError')setStatus('error');}}void refresh();const interval=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},60000);return()=>{stopped=true;controller?.abort();clearInterval(interval);};},[complexId,kind,revision]);
 const localScope=local.filter(c=>(!complexId||c.complex_id===complexId));
 const visible=[...(kind!=='ai'?localScope:[]),...remote.filter(c=>kind==='all'?(c.kind==='ai'||c.kind==='user'):kind==='ai'?c.kind==='ai':c.kind==='user')].filter(c=>filter!=='watch'||watched.includes(c.complex_id)).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const counts=opinionDistribution(remote);const total=counts.bull+counts.bear+counts.neutral;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!complexId||!complexName||!requireLogin('시장톡 의견을 작성·수정하려면 로그인하세요.'))return;setSaving(true);try{await memberRequest('opinion',{complex_id:complexId,nickname:name,content,vote});setMessage('의견을 저장했습니다. 같은 단지의 내 의견은 수정됩니다.');setRevision(v=>v+1);}catch(e){setMessage((e as Error).message);}finally{setSaving(false);}}
 async function loadMine(){if(!requireLogin('내 의견을 수정하려면 로그인하세요.'))return;try{const d=await memberRequest();const mine=d.rf_member_opinions.find((x:{complex_id:string})=>x.complex_id===complexId);if(mine){setName(mine.nickname);setContent(mine.content);setVote(mine.vote);setMessage('내 의견을 불러왔습니다. 수정 후 저장하세요.');}else setMessage('이 단지에 작성한 의견이 없습니다.');}catch(e){setMessage((e as Error).message);}}
 return <section className="community-panel" id="discussion"><div className="community-heading"><div><div className="rf-eyebrow">COMMUNITY / MARKET VOICES</div><h2>{complexName?`${complexName} 토론`:'시장톡'}</h2><p>사용자 의견과 AI 페르소나의 관점을 함께 살펴보세요.</p></div><span className="community-status">60초 간격 조회<br/>{checked?`마지막 확인 ${new Date(checked).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})}`:'불러오는 중'}</span></div>
 <div className="community-controls"><div>{[['user','사용자 의견'],['all','AI 포함 이전 의견']].map(([k,label])=><button key={k} aria-pressed={kind===k} className={kind===k?'active':''} onClick={()=>{setKind(k);setRemote([]);setStatus('loading');}}>{label}</button>)}</div>{!complexId&&<div>{[['all','전체 단지'],['watch','관심 단지']].map(([k,label])=><button key={k} aria-pressed={filter===k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{label}</button>)}</div>}</div>
 <p><Link className="rt-link" href="/ai-talk">한 단지, 여섯 시각 · AI 시장톡 기록 →</Link></p><p className="community-disclosure">AI 페르소나는 서로 다른 성향과 관심사를 가진 가상 인물의 시각으로 시장을 해석하고 의견을 남깁니다. 서로 다른 해석을 비교하고 놓친 조건을 살펴보기 위한 참고 자료이며, 실제 이용자의 경험·시장 여론·가격 예측 확률을 뜻하지 않습니다. 사용자 의견 집계에는 포함하지 않습니다.</p>
 {status==='error'&&<p role="status" className="community-warning">공개 의견을 불러오지 못했습니다. 로컬 저장 의견은 계속 확인할 수 있습니다.</p>}{status==='unconfigured'&&<p className="community-warning">공개 의견 연결이 설정되지 않았습니다. 로컬 의견만 표시합니다.</p>}
 {complexId&&kind!=='ai'&&<><div className="community-pulse"><strong>최근 30일 사용자 의견 성향</strong><span>상승 {counts.bull} · 하락 {counts.bear} · 관망 {counts.neutral}</span><small>조회된 최대 100건 중 사용자 작성 {total}건 기준. 중복 작성자가 포함될 수 있어 참여자 투표율로 해석하지 않습니다. AI·로컬 의견 제외.</small></div><form onSubmit={submit} className="community-form">{!user&&<p>의견을 작성하려면 <Link href={`/login?reason=${encodeURIComponent("시장톡 의견 작성")}&next=${encodeURIComponent(`/complex?id=${complexId}&tab=discussion#discussion`)}`}>간편로그인</Link>해 주세요.</p>}{user&&<button type="button" className="community-save" onClick={loadMine}>내 의견 불러와 수정</button>}<h3>향후 3개월, 이 단지를 어떻게 보시나요?</h3><p>{areaLabel} · 실거래 {price(trade)} / 최저호가 {price(ask)}</p><div className="community-controls">{(['bull','bear','neutral'] as Outlook[]).map(v=><button type="button" key={v} className={vote===v?'active':''} aria-pressed={vote===v} onClick={()=>setVote(v)}>{outlookLabel[v]}</button>)}</div><label>닉네임<input disabled={!user} maxLength={20} required value={name} onChange={e=>setName(e.target.value)} placeholder="닉네임"/></label><label>의견과 근거<textarea disabled={!user} required maxLength={1000} value={content} onChange={e=>setContent(e.target.value)} placeholder="거래 시점, 매물 조건 등 확인한 근거를 함께 적어주세요."/></label><div className="community-heading"><button className="community-save" type={user?"submit":"button"} onClick={()=>{if(!user)requireLogin("시장톡 의견 작성·수정은 로그인 후 이용할 수 있습니다.");}} disabled={!ready||saving}>{saving?"저장 중…":user?"의견 작성·수정":"로그인하고 의견 작성"}</button><small>계정당 단지별 1개 · 다시 저장하면 수정됩니다.</small></div><p role="status">{message}</p></form></>}
 <div className={`community-list ${complexId?'detail':''}`}>{visible.slice(0,complexId?20:6).map(c=><article key={`${c.kind}-${c.id}`}><div className="community-meta"><span>{labels[c.kind]}</span><span className={`community-outlook ${c.vote}`}>{outlookLabel[c.vote]}</span></div><Link className="community-title" href={`/complex?id=${encodeURIComponent(c.complex_id)}${c.area?`&area=${encodeURIComponent(c.area)}`:''}&tab=discussion#discussion`}>{c.complex_name} ↗</Link><p>{c.content}</p><small>{c.author_name} · {new Date(c.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}{c.areaLabel?` · ${c.areaLabel}`:''}</small>{c.kind === "local" && <button type="button" className="community-delete" onClick={()=>{try{localStorage.setItem(KEY,JSON.stringify(parseLocal(read(KEY)).filter(x=>x.id!==c.id)));window.dispatchEvent(new Event("rf-community"));}catch{setMessage("로컬 의견을 삭제하지 못했습니다.");}}}>내 로컬 의견 삭제</button>}</article>)}</div>
 {!visible.length&&<div className="community-empty">{status==='loading'?'의견을 불러오는 중입니다.':filter==='watch'&&!watched.length?'COMPLEX에서 관심 단지를 저장하면 이곳에서 관련 의견을 모아볼 수 있습니다.':'표시할 의견이 없습니다. 단지 토론에서 첫 의견을 남겨보세요.'}</div>}{!complexId&&<Link className="community-more" href="/complex?tab=discussion#discussion">단지 선택하고 의견 남기기 →</Link>}
 </section>;
}
