 'use client';
import {useState} from 'react';
import {createPortal} from 'react-dom';
export default function FeedbackButton(){const [open,setOpen]=useState(false),[page,setPage]=useState('/'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 function show(){const u=new URL(window.location.href),q=new URLSearchParams();for(const k of ['id','area','date']){const v=u.searchParams.get(k);if(v)q.set(k,v);}setPage((u.pathname+(q.size?'?'+q.toString():'' )).slice(0,300));setMessage('');setDone(false);setOpen(true);}
 return <><button type="button" className="rt-button" onClick={show}>의견·오류 제보</button>{open&&createPortal(<div className="feedback-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="feedback-title" className="feedback-dialog" onKeyDown={e=>{if(e.key==='Escape'&&!busy)setOpen(false);}}><h2 id="feedback-title">의견·오류 제보</h2><p>운영자에게만 전달됩니다. 비밀번호·인증번호 등 민감한 정보는 적지 마세요.</p>{!done&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(f),page,consent:f.get('consent')==='on'})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDone(true);setMessage('접수했습니다. 보내주신 의견을 검토하겠습니다.');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}>
 <label>분류<select name="category" autoFocus><option>데이터 오류</option><option>사용 불편</option><option>기능 제안</option></select></label><label>내용<textarea name="content" required minLength={10} maxLength={3000} rows={5} placeholder="어느 부분이 불편했는지 알려주세요. (10자 이상)"/></label><label>답변받을 이메일 (선택)<input name="email" type="email" maxLength={254}/></label><input name="website" tabIndex={-1} autoComplete="off" className="feedback-honey" aria-hidden="true"/>
 <p>함께 전달할 페이지·단지: <code>{page}</code></p><label className="feedback-consent"><input name="consent" type="checkbox" required/> 의견 처리와 답변을 위해 내용·현재 페이지 및 선택한 단지·입력한 이메일을 수집하는 데 동의합니다. 접수일로부터 90일간 보관합니다. 동의하지 않으면 접수할 수 없습니다.</label><button className="rt-button" disabled={busy}>{busy?'접수 중…':'의견 보내기'}</button></form>}<p role="status">{message}</p><button type="button" className="rt-button secondary" disabled={busy} onClick={()=>setOpen(false)}>닫기</button></section></div>,document.body)}</>;
}
