'use client';
import { useState } from 'react';
import Link from 'next/link';
import { CartesianGrid, ComposedChart, Line, Bar, ScatterChart, Scatter, ResponsiveContainer, ReferenceLine, Tooltip, XAxis, YAxis } from 'recharts';
import type { MarketData, MacroPoint } from '@/lib/market-data';
import { percent, price } from '@/lib/complex-model';
const tip = { background: '#13212c', border: '1px solid #3d5262', borderRadius: 7, color: '#d9e6ef', fontSize: 12 };
export function TrendChart({ data }: {
    data: MacroPoint[];
}) { return <div className="rt-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 10, right: 2, left: -20, bottom: 0 }}><CartesianGrid stroke="#253442" vertical={false}/><XAxis dataKey="month" stroke="#91a5b7" tick={{ fontSize: 10 }} minTickGap={40}/><YAxis yAxisId="price" stroke="#91a5b7" tick={{ fontSize: 10 }} domain={['auto', 'auto']} unit="%"/><YAxis yAxisId="volume" orientation="right" stroke="#648177" tick={{ fontSize: 10 }}/><Tooltip contentStyle={tip} itemStyle={{ color: "#d9e6ef" }} labelStyle={{ color: "#d9e6ef" }}/><Bar isAnimationActive={false} dataKey="sample_count" name="월 신고 거래 수(건)" yAxisId="volume" fill="#35574f" radius={[3, 3, 0, 0]}/><Line isAnimationActive={false} dataKey="recovery_rate" name="월 실거래 회복률(%)" yAxisId="price" stroke="#a6c8f4" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div>; }
type Row = MarketData['rows'][number];
export function Matrix({ rows }: {
    rows: Row[];
}) { const [selected, setSelected] = useState<Row | null>(null); const data = rows.filter(r => r.gap !== null && r.drop !== null && r.age !== null && r.age <= 365); return <><div className="rt-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 15, right: 20, left: 5, bottom: 18 }}><CartesianGrid stroke="#273541"/><XAxis type="number" dataKey="drop" name="고점 대비 실거래" unit="%" stroke="#91a5b7" tick={{ fontSize: 10 }} label={{ value: '고점 대비 최근 실거래 (%)', position: 'insideBottom', offset: -13, fill: '#95aaba', fontSize: 11 }}/><YAxis type="number" dataKey="gap" name="호가 괴리" unit="%" stroke="#91a5b7" tick={{ fontSize: 10 }}/><ReferenceLine y={0} stroke="#829d9f" strokeDasharray="4 4"/><Tooltip cursor={{ strokeDasharray: '3 3' }} content={({ active, payload }) => active && payload?.length ? <div style={{ ...tip, padding: 12 }}><b>{payload[0].payload.name}</b><p>고점 대비 {percent(payload[0].payload.drop)}</p><p>호가 괴리 {percent(payload[0].payload.gap)}</p></div> : null}/><Scatter isAnimationActive={false} data={data} fill="#8fe0c6" onClick={(point) => setSelected(point.payload as Row)}/></ScatterChart></ResponsiveContainer></div><p className="rt-caption">세로축: 현재 호가와 최근 거래의 차이 · 가로축: 관측 고점 대비 실거래. 점을 선택하거나 아래 표에서 단지를 탐색하세요.</p>{selected && <div className="rt-list-row"><div><strong>{selected.name}</strong><small>{selected.areaLabel} · 실거래 {price(selected.trade)} / 호가 {price(selected.ask)}</small></div><Link className="rt-link" href={`/complex?id=${selected.id}&area=${encodeURIComponent(selected.area)}`}>단지 분석 →</Link></div>}</>; }
export function MarketTable({ rows }: {
    rows: Row[];
}) { const [query, setQuery] = useState(''); const [sort, setSort] = useState('gap'); const filtered = rows.filter(r => `${r.name} ${r.address}`.includes(query)).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'ko') : sort === 'gap_low' ? (a.gap ?? Infinity) - (b.gap ?? Infinity) : sort === 'drop' ? (a.drop ?? Infinity) - (b.drop ?? Infinity) : (b.gap ?? -Infinity) - (a.gap ?? -Infinity)); return <><div className="rt-controls"><input aria-label="단지명 또는 지역 검색" value={query} onChange={e => setQuery(e.target.value)} placeholder="단지명 또는 지역 검색"/><select aria-label="단지 정렬" value={sort} onChange={e => setSort(e.target.value)}><option value="gap">호가 괴리 큰 순</option><option value="gap_low">호가 괴리 낮은 순</option><option value="drop">고점 대비 낙폭 순</option><option value="name">단지명 순</option></select><span className="rt-small">{filtered.length}개 항목</span></div><div className="rt-table-wrap"><table className="rt-table"><thead><tr><th>단지 / 타입</th><th>최근 실거래</th><th>현재 최저호가</th><th>호가 괴리</th><th>고점 대비 실거래</th></tr></thead><tbody>{filtered.map(r => <tr key={`${r.id}:${r.area}`}><td><Link href={`/complex?id=${r.id}&area=${encodeURIComponent(r.area)}`}>{r.name} ↗</Link><small>{r.areaLabel}</small></td><td>{price(r.trade)}<small>{r.tradeDate}{(r.age ?? Infinity) > 365 ? ' · 장기 미거래' : ''}</small></td><td>{price(r.ask)}</td><td className="rf-mint">{percent(r.gap)}</td><td className="rf-blue">{percent(r.drop)}</td></tr>)}</tbody></table>{!filtered.length && <div className="rt-empty">검색 결과가 없습니다.</div>}</div></>; }
