import {memberIdentity,sameOrigin} from '@/lib/member-server';
import {readComplex,readUniverse} from '@/lib/complex-data';
import {areaKey,positive,price} from '@/lib/complex-model';
import {readReport} from '@/lib/report-data';
import {createHash} from 'node:crypto';
export const dynamic='force-dynamic';
const failure=()=>Response.json({error:'회원 저장소 연결을 확인해 주세요. 아직 저장되지 않았습니다.'},{status:503});
export async function GET(req:Request){const auth=await memberIdentity(req);if(!auth)return Response.json({error:'로그인이 필요합니다.'},{status:401});const {client,user}=auth;const names=['rf_profiles','rf_watchlist','rf_saved_reports','rf_alert_rules','rf_notifications','rf_member_opinions'];const results=await Promise.all(names.map(n=>client.from(n).select('*').eq('user_id',user.id).limit(200)));if(results.some(r=>r.error))return failure();const rules=results[names.indexOf('rf_alert_rules')];rules.data=await Promise.all((rules.data||[]).map(async rule=>{const detail=await readComplex(rule.complex_id);return {...rule,data_updated_at:detail?.updatedAt};}));return Response.json(Object.fromEntries(names.map((n,i)=>[n,results[i].data])),{headers:{'Cache-Control':'no-store'}});}
export async function POST(req:Request){if(!sameOrigin(req))return Response.json({error:'허용되지 않은 요청입니다.'},{status:403});const auth=await memberIdentity(req);if(!auth)return Response.json({error:'로그인이 필요합니다.'},{status:401});const {client,user}=auth;try{const raw=await req.text();if(raw.length>12000)return Response.json({error:'입력이 너무 깁니다.'},{status:413});const b=JSON.parse(raw);const uid=user.id;let result;
if(b.action==='profile'){const nickname=String(b.nickname||'').trim();if(nickname.length<2||nickname.length>20)throw new Error('닉네임은 2~20자입니다.');result=await client.from('rf_profiles').upsert({user_id:uid,nickname},{onConflict:'user_id'});}
else if(b.action==='watch'){const {summaries}=await readUniverse();const c=summaries.find(x=>x.id===b.complex_id);if(!c)throw new Error('단지를 찾을 수 없습니다.');result=b.enabled?await client.from('rf_watchlist').upsert({user_id:uid,complex_id:c.id,label:c.name},{onConflict:'user_id,complex_id'}):await client.from('rf_watchlist').delete().eq('user_id',uid).eq('complex_id',c.id);}
else if(b.action==='report'){if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date||''))throw new Error('발행된 리포트만 저장할 수 있습니다.');const report=await readReport(b.date);if(!report.document||report.document.date!==b.date)throw new Error('리포트를 찾을 수 없습니다.');result=b.remove?await client.from('rf_saved_reports').delete().eq('user_id',uid).eq('report_date',b.date):await client.from('rf_saved_reports').upsert({user_id:uid,report_date:b.date,label:report.document.report.title},{onConflict:'user_id,report_date'});}
else if(b.action==='opinion'){const {summaries}=await readUniverse();if(!summaries.some(x=>x.id===b.complex_id))throw new Error('단지를 찾을 수 없습니다.');const nickname=String(b.nickname||'').trim(),content=String(b.content||'').trim();if(nickname.length<2||nickname.length>20||content.length<5||content.length>1000||!['bull','bear','neutral'].includes(b.vote))throw new Error('닉네임 2~20자와 의견 5~1000자, 전망을 확인하세요.');result=await client.from('rf_member_opinions').upsert({user_id:uid,complex_id:b.complex_id,nickname,content,vote:b.vote,updated_at:new Date().toISOString()},{onConflict:'user_id,complex_id'});}
else if(b.action==='alert'){const detail=await readComplex(String(b.complex_id));const stat=detail?.stats.find(s=>areaKey(s)===b.area);const threshold=Number(b.threshold);if(!detail||!stat||!positive(stat.current_lowest_ask)||!Number.isFinite(threshold)||threshold<1||threshold>30)throw new Error('호가가 있는 타입과 1~30% 기준을 선택하세요.');result=await client.from('rf_alert_rules').upsert({user_id:uid,complex_id:b.complex_id,area:b.area,label:detail.complex.name,threshold,baseline:stat.current_lowest_ask,created_at:new Date().toISOString(),enabled:true},{onConflict:'user_id,complex_id,area'});}
else if(b.action==='remove'){const tables:Record<string,string>={alert:'rf_alert_rules',notification:'rf_notifications',opinion:'rf_member_opinions'};if(!tables[b.kind])throw new Error('지원하지 않는 항목입니다.');result=await client.from(tables[b.kind]).delete().eq('user_id',uid).eq('id',String(b.id));}
else if(b.action==='check_alerts'){const rules=await client.from('rf_alert_rules').select('*').eq('user_id',uid).eq('enabled',true).limit(200);if(rules.error)return failure();for(const rule of rules.data||[]){const d=await readComplex(rule.complex_id);const stat=d?.stats.find(s=>areaKey(s)===rule.area);if(!d||!stat||!positive(stat.current_lowest_ask)||!positive(rule.baseline))continue;const delta=(stat.current_lowest_ask/rule.baseline-1)*100;if(Math.abs(delta)<rule.threshold)continue;const fingerprint=createHash('sha256').update(`${rule.id}:${rule.baseline}:${stat.current_lowest_ask}`).digest('hex');const save=await client.from('rf_notifications').upsert({user_id:uid,rule_id:rule.id,fingerprint,message:`${rule.label} · 설정 당시 ${price(rule.baseline)} → 현재 ${price(stat.current_lowest_ask)} (${delta>0?'+':''}${delta.toFixed(1)}%)`,complex_id:rule.complex_id,area:rule.area},{onConflict:'user_id,fingerprint',ignoreDuplicates:true});if(save.error)return failure();}return Response.json({ok:true});}
else throw new Error('지원하지 않는 작업입니다.');if(result?.error)return failure();return Response.json({ok:true});
}catch(e){return Response.json({error:e instanceof SyntaxError?'입력 형식을 확인하세요.':e instanceof Error&&!('code'in e)?e.message:'처리하지 못했습니다.'},{status:400});}}
